CREATE OR ALTER PROCEDURE [dbo].[spsys_GetProcedureParams] @ProcedureName VARCHAR(128) 
AS
BEGIN
SELECT       ORDINAL_POSITION, 
             PARAMETER_NAME,
			 DATA_TYPE,
			 PARAMETER_MODE, 
			 CHARACTER_MAXIMUM_LENGTH, 
             CHARACTER_OCTET_LENGTH, 
			 NUMERIC_PRECISION, 
			 NUMERIC_SCALE

FROM         INFORMATION_SCHEMA.PARAMETERS AS R
WHERE        (SPECIFIC_NAME = @ProcedureName)

ORDER BY ORDINAL_POSITION
END

GO



